// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package enums

import (
	"fmt"
	"strings"
)

const (
	TaskTypeCask      TaskType = "cask"
	TaskTypeCellar    TaskType = "cellar"
	TaskTypeBrew      TaskType = "brew"
	TaskTypeDir       TaskType = "dir"
	TaskTypeFunction  TaskType = "function"
	TaskTypeGit       TaskType = "git"
	TaskTypeLink      TaskType = "link"
	TaskTypeJetbrains TaskType = "jetbrains"
	TaskTypeMas       TaskType = "mas"
	TaskTypeVscode    TaskType = "vscode"
	TaskTypeBash      TaskType = "bash"
)

var ErrInvalidTaskType = fmt.Errorf("not a valid TaskType, try [%s]", strings.Join(_TaskTypeNames, ", "))

var _TaskTypeNames = []string{
	string(TaskTypeCask),
	string(TaskTypeCellar),
	string(TaskTypeBrew),
	string(TaskTypeDir),
	string(TaskTypeFunction),
	string(TaskTypeGit),
	string(TaskTypeLink),
	string(TaskTypeJetbrains),
	string(TaskTypeMas),
	string(TaskTypeVscode),
	string(TaskTypeBash),
}

// TaskTypeNames returns a list of possible string values of TaskType.
func TaskTypeNames() []string {
	tmp := make([]string, len(_TaskTypeNames))
	copy(tmp, _TaskTypeNames)
	return tmp
}

// TaskTypeValues returns a list of the values for TaskType
func TaskTypeValues() []TaskType {
	return []TaskType{
		TaskTypeCask,
		TaskTypeCellar,
		TaskTypeBrew,
		TaskTypeDir,
		TaskTypeFunction,
		TaskTypeGit,
		TaskTypeLink,
		TaskTypeJetbrains,
		TaskTypeMas,
		TaskTypeVscode,
		TaskTypeBash,
	}
}

// String implements the Stringer interface.
func (x TaskType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TaskType) IsValid() bool {
	_, err := ParseTaskType(string(x))
	return err == nil
}

var _TaskTypeValue = map[string]TaskType{
	"cask":      TaskTypeCask,
	"cellar":    TaskTypeCellar,
	"brew":      TaskTypeBrew,
	"dir":       TaskTypeDir,
	"function":  TaskTypeFunction,
	"git":       TaskTypeGit,
	"link":      TaskTypeLink,
	"jetbrains": TaskTypeJetbrains,
	"mas":       TaskTypeMas,
	"vscode":    TaskTypeVscode,
	"bash":      TaskTypeBash,
}

// ParseTaskType attempts to convert a string to a TaskType.
func ParseTaskType(name string) (TaskType, error) {
	if x, ok := _TaskTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _TaskTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return TaskType(""), fmt.Errorf("%s is %w", name, ErrInvalidTaskType)
}

// MustParseTaskType converts a string to a TaskType, and panics if is not valid.
func MustParseTaskType(name string) TaskType {
	val, err := ParseTaskType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x TaskType) Ptr() *TaskType {
	return &x
}

// MarshalText implements the text marshaller method.
func (x TaskType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *TaskType) UnmarshalText(text []byte) error {
	tmp, err := ParseTaskType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *TaskType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

// Set implements the Golang flag.Value interface func.
func (x *TaskType) Set(val string) error {
	v, err := ParseTaskType(val)
	*x = v
	return err
}

// Get implements the Golang flag.Getter interface func.
func (x *TaskType) Get() interface{} {
	return *x
}

// Type implements the github.com/spf13/pFlag Value interface.
func (x *TaskType) Type() string {
	return "TaskType"
}
