// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package plays

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlayBookInfo creates a new instance of MockPlayBookInfo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlayBookInfo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlayBookInfo {
	mock := &MockPlayBookInfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlayBookInfo is an autogenerated mock type for the PlayBookInfo type
type MockPlayBookInfo struct {
	mock.Mock
}

type MockPlayBookInfo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayBookInfo) EXPECT() *MockPlayBookInfo_Expecter {
	return &MockPlayBookInfo_Expecter{mock: &_m.Mock}
}

// GetID provides a mock function for the type MockPlayBookInfo
func (_mock *MockPlayBookInfo) GetID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPlayBookInfo_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type MockPlayBookInfo_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *MockPlayBookInfo_Expecter) GetID() *MockPlayBookInfo_GetID_Call {
	return &MockPlayBookInfo_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *MockPlayBookInfo_GetID_Call) Run(run func()) *MockPlayBookInfo_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayBookInfo_GetID_Call) Return(s string) *MockPlayBookInfo_GetID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPlayBookInfo_GetID_Call) RunAndReturn(run func() string) *MockPlayBookInfo_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetJetBrainsApps provides a mock function for the type MockPlayBookInfo
func (_mock *MockPlayBookInfo) GetJetBrainsApps() map[string]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetJetBrainsApps")
	}

	var r0 map[string]string
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	return r0
}

// MockPlayBookInfo_GetJetBrainsApps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJetBrainsApps'
type MockPlayBookInfo_GetJetBrainsApps_Call struct {
	*mock.Call
}

// GetJetBrainsApps is a helper method to define mock.On call
func (_e *MockPlayBookInfo_Expecter) GetJetBrainsApps() *MockPlayBookInfo_GetJetBrainsApps_Call {
	return &MockPlayBookInfo_GetJetBrainsApps_Call{Call: _e.mock.On("GetJetBrainsApps")}
}

func (_c *MockPlayBookInfo_GetJetBrainsApps_Call) Run(run func()) *MockPlayBookInfo_GetJetBrainsApps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayBookInfo_GetJetBrainsApps_Call) Return(stringToString map[string]string) *MockPlayBookInfo_GetJetBrainsApps_Call {
	_c.Call.Return(stringToString)
	return _c
}

func (_c *MockPlayBookInfo_GetJetBrainsApps_Call) RunAndReturn(run func() map[string]string) *MockPlayBookInfo_GetJetBrainsApps_Call {
	_c.Call.Return(run)
	return _c
}
